kind : Deployment
apiVersion: app/v1
metadata:
  name: nginx-deployment
  namespace: nginix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginix
    
  template:
    metadata:
      name: nginx-dep-pod
      labels:
        app: nginx
      spec:
        containers:
          -name: nginx
          image: nginx
          ports:
            - containerPort: 80


