apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginix
  template:
    metadata:
      name: nginx-dep-pod
      labels:
        app: nginix
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: local-pvc

