kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: nginix
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes: 
   - ReadWriteOnce
  storageClassName: local-storage
