kind: deployments
apiVersion: app/v1
metadata:
  name: nginx-deployment
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

      ----
    
template:
     metadata:
        name: nginx-dep-pod
        labels:
          app: nginx # lables given to pod 
        spec:
          containers:
            - name: nginx
              image: nginx
              ports:
                - containerPort : 80


