apiVersion: v1
kind: Namespace
metadata:
  name: nginix
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginix
spec:
  containers:
  -name: nginx
    image: nginx 
    ports: 
    - containerPort: 80
    
