apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-replicaset
  namespace: nginix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-replics
        image: nginx
        ports:
        - containerPort: 80

